# Generated by Django 3.2.6 on 2022-01-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_eturf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorydb',
        ),
    ]
