# Generated by Django 3.2.6 on 2022-01-20 06:05

from django.db import migrations, models
import tkinter.tix


class Migration(migrations.Migration):

    dependencies = [
        ('admin_eturf', '0002_rename_category_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playgroungddb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='playground')),
                ('ground', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=tkinter.tix.Tree)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
