# Generated by Django 3.2.6 on 2022-01-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_eturf', '0003_playgroungddb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playgroungddb',
            new_name='Playgrounddb',
        ),
    ]
