# Generated by Django 3.2.6 on 2022-01-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_eturf', '0004_rename_playgroungddb_playgrounddb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
