# Generated by Django 3.2.6 on 2022-01-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_eturf', '0005_managerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdb',
            name='playground',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
