# Generated by Django 3.2.6 on 2022-01-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_eturf', '0006_managerdb_playground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerdb',
            name='image',
            field=models.ImageField(null=True, upload_to='manager'),
        ),
    ]
