# Generated by Django 3.2.7 on 2022-01-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_eturf', '0007_alter_managerdb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgrounddb',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
