# Generated by Django 3.2.7 on 2022-01-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_eturf', '0008_alter_playgrounddb_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='playgrounddb',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
