# Generated by Django 3.2.7 on 2022-02-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eturf_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdb',
            unique_together={('username', 'email')},
        ),
    ]
