# Generated by Django 3.2.7 on 2022-02-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_eturf', '0009_playgrounddb_price'),
        ('eturf_web', '0003_auto_20220206_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='managerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_eturf.managerdb'),
        ),
    ]
