# Generated by Django 3.2.6 on 2022-03-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eturf_web', '0004_bookdb_managerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
